# Generated by Django 2.2 on 2020-05-20 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200519_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AddField(
            model_name='account',
            name='is_trusty',
            field=models.BooleanField(default=False, verbose_name='trusty'),
        ),
    ]
