# Generated by Django 2.2 on 2020-05-10 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topic', '0001_initial'),
        ('role', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Replay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('kind_speech', models.CharField(choices=[('PE', 'Pergunto'), ('SU', 'Sugiro'), ('AD', 'Além disso'), ('CM', 'Comento'), ('ACT', 'Acrescento'), ('INF', 'Informo'), ('RP', 'Respondo'), ('CD', 'Concordo'), ('DIS', 'Discordo'), ('PRQ', 'Para que'), ('PQ', 'Porque'), ('PC', 'Peço'), ('EX', 'Explico'), ('EXF', 'Exemplifico'), ('NE', 'Não entendi'), ('E', 'E'), ('ET', 'Então'), ('OU', 'Ou'), ('MAS', 'Mas'), ('CNM', 'Concordo mas'), ('DSM', 'Discordo mas'), ('CON', 'Continuo'), ('TRN', 'Transcrevo')], default='E', max_length=2, verbose_name='Tipo de fala')),
                ('url_details', models.TextField(blank=True, verbose_name='uri')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replays', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('roles_for', models.ManyToManyField(to='role.Role', verbose_name='Para o papel')),
                ('roles_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replays_in', to='role.Role', verbose_name='No papel')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replays', to='topic.Topic', verbose_name='Topic')),
            ],
            options={
                'db_table': 'replay',
            },
        ),
    ]
