# Generated by Django 2.2 on 2020-12-17 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import replay.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('topic', '0001_initial'),
        ('role', '0003_remove_role_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Replay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('kind_speech', models.CharField(choices=[('PE', 'Pergunto'), ('SU', 'Sugiro'), ('AD', 'Além disso'), ('CM', 'Comento'), ('ACT', 'Acrescento'), ('INF', 'Informo'), ('RP', 'Respondo'), ('CD', 'Concordo'), ('DIS', 'Discordo'), ('PRQ', 'Para que'), ('PQ', 'Porque'), ('PC', 'Peço'), ('EX', 'Explico'), ('EXF', 'Exemplifico'), ('NE', 'Não entendi'), ('E', 'E'), ('ET', 'Então'), ('OU', 'Ou'), ('MAS', 'Mas'), ('CNM', 'Concordo mas'), ('DSM', 'Discordo mas'), ('CON', 'Continuo'), ('TRN', 'Transcrevo')], default='E', max_length=10, verbose_name='Tipo de fala')),
                ('image_details', models.ImageField(blank=True, max_length=255, null=True, upload_to=replay.models.directory_path)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replays', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('roles_for', models.ManyToManyField(related_name='replays_for', to='role.Role', verbose_name='Para o papel')),
                ('roles_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replays_in', to='role.Role', verbose_name='No papel')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replays', to='topic.Topic', verbose_name='Topic')),
            ],
            options={
                'db_table': 'replay',
            },
        ),
    ]
