# Generated by Django 2.2 on 2020-07-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replay',
            name='kind_speech',
            field=models.CharField(choices=[('PE', 'Pergunto'), ('SU', 'Sugiro'), ('AD', 'Além disso'), ('CM', 'Comento'), ('ACT', 'Acrescento'), ('INF', 'Informo'), ('RP', 'Respondo'), ('CD', 'Concordo'), ('DIS', 'Discordo'), ('PRQ', 'Para que'), ('PQ', 'Porque'), ('PC', 'Peço'), ('EX', 'Explico'), ('EXF', 'Exemplifico'), ('NE', 'Não entendi'), ('E', 'E'), ('ET', 'Então'), ('OU', 'Ou'), ('MAS', 'Mas'), ('CNM', 'Concordo mas'), ('DSM', 'Discordo mas'), ('CON', 'Continuo'), ('TRN', 'Transcrevo')], default='E', max_length=10, verbose_name='Tipo de fala'),
        ),
    ]
