# Generated by Django 2.2 on 2020-10-17 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_project_created_by'),
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='project',
        ),
        migrations.AddField(
            model_name='role',
            name='project',
            field=models.ManyToManyField(related_name='roles', to='project.Project'),
        ),
    ]
