# Generated by Django 2.2 on 2020-10-17 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0003_remove_role_project'),
        ('project', '0002_remove_project_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='roles',
            field=models.ManyToManyField(related_name='projects', to='role.Role'),
        ),
    ]
